language: go
sudo: false
go:
  - 1.8
  - tip

before_install:
  - go get -t -u ./...

script:
  - ./go.test.sh

after_success:
  - cp build/coverage.txt ./
  - bash <(curl -s https://codecov.io/bash)
